[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
token_transfer_contract = "ASR2KSdgBuAu9HRJtEEMhrtSXSXVySJFhBzZkx1z57At"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
